### ISSUE TITLE
Unable to run the project in Eclipse.

### ISSUE THREAD

**Issue by cegprakash** [lovrop/topcoder-moj#3]
Exception in thread "main" java.lang.NullPointerException
    at moj.ConfigurationDialog.<init>(ConfigurationDialog.java:54)
    at moj.ConfigurationDialog.main(ConfigurationDialog.java:186)

**Comment by lovrop** [comment]
Can you tell me what you were trying to do?

**Comment by cegprakash** [comment]
I was searching for a TC plugin which uses sublime. I just was trying to
create the JAR.

I imported the project in Eclipse in my Mac machine and it produces that
error when I run.

**Comment by lovrop** [comment]
Can you just download the bundle from https://github.com/lovrop/topcoder-moj/releases/ ?

**Comment by cegprakash** [comment]
Got the jar! I don't know the entry point I should give in codeprocessor
for sublime text editor. Could you plz tell me the steps to make it work
with Sublime in Mac?

**Comment by lovrop** [comment]
Setup steps are described in README: https://github.com/lovrop/topcoder-moj/blob/v4.18/README#L60
